# Generated by Django 6.0.6 on 2026-09-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aplicaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoJuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipojuego", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Juegos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "instalar",
                    models.CharField(
                        choices=[("NO", "NO"), ("SI", "SI")], default="NO", max_length=2
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicaciones.origen",
                    ),
                ),
                (
                    "tipojuego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="juegos.tipojuego",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
