# Generated by Django 6.0.6 on 2026-09-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("juegos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="juegos",
            old_name="tipojuego",
            new_name="tipoJuego",
        ),
        migrations.RenameField(
            model_name="tipojuego",
            old_name="tipojuego",
            new_name="tipoJuego",
        ),
    ]
