# Generated by Django 6.0.6 on 2026-09-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("anyo", models.IntegerField()),
                ("notas", models.CharField(max_length=100)),
                (
                    "copiado",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")], default="NO", max_length=2
                    ),
                ),
                (
                    "falta",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")], default="SI", max_length=2
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cds.grupo"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cds.tipo"
                    ),
                ),
            ],
            options={
                "ordering": ("grupo", "titulo"),
            },
        ),
    ]
