# Generated by Django 6.0.6 on 2026-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cds",
            name="notas",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
