# Generated by Django 6.0.6 on 2026-06-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subtipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtipo", models.CharField(max_length=60)),
                ("descripcion", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=60)),
                ("descripcion", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="LibroInformatica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("editorial", models.CharField(max_length=200)),
                ("anyo", models.IntegerField()),
                (
                    "leido",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")], default="NO", max_length=2
                    ),
                ),
                (
                    "subtipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="libro_informatica.subtipo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="libro_informatica.tipo",
                    ),
                ),
            ],
            options={
                "ordering": ("titulo",),
            },
        ),
    ]
