# Generated by Django 6.0.6 on 2026-09-18 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Origen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Aplicaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aplicacion", models.CharField(max_length=200)),
                (
                    "instalar",
                    models.CharField(
                        choices=[("NO", "NO"), ("SI", "SI")], default="SI", max_length=2
                    ),
                ),
                (
                    "favoritos",
                    models.CharField(
                        choices=[("NO", "NO"), ("SI", "SI")], default="NO", max_length=2
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplicaciones.origen",
                    ),
                ),
            ],
            options={
                "ordering": ["aplicacion"],
            },
        ),
    ]
