# Generated by Django 6.0.6 on 2026-07-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibroElectronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("serie", models.CharField(max_length=200)),
                (
                    "bajado",
                    models.CharField(
                        choices=[("NO", "NO"), ("SI", "SI")], default="NO", max_length=2
                    ),
                ),
                ("notas", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ("titulo",),
            },
        ),
    ]
